version: '3'

tasks:
  dev:
    desc: run everything needed for development
    deps: [install, generate]
    watch: true

  tidy:
    cmds:
      - go mod tidy

  build:
    cmds:
      - go build ./...

  install:
    desc: install the local mojave build to the bin directory
    sources:
      - './**/*.go'
      - 'go.mod'
      - 'go.sum'
    deps: [tidy, build]
    cmds:
      - cd cmd/mojave && go install .

  generate:
    cmds:
      - buf generate
    deps: [buf-lint]
    sources:
      - './proto/**/*.proto'

  buf-lint:
    cmds:
      - buf lint